remote_theme: pmarsceill/just-the-docs

aux_links:
  "latphone library on GitHub":
    - "//github.com/neelsmith/latphone"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
