


# Permalinks
permalink:        pretty

# Setup
title:            Latin orthography and phonology
tagline:          'Work with texts in Latin'
description:      'A library for working phonologically with texts in a specified Latin orthography'


baseurl: '/latphone/'


author:
  name:           'Neel Smith'


links:
  - title:  Github repository
    url:  https://github.com/neelsmith/latphone
    external: true
